### ISSUE TITLE
Not working Kali 2019.1

### ISSUE THREAD

**Issue by ramvirsingh660** [the-c0d3r/admin-finder#11]
root@kali:~/Desktop/Data/admin-finder# ls
admin-finder.py  lib  LICENSE  log  README.md  robot.txt  wordlist.txt
root@kali:~/Desktop/Data/admin-finder# perl admin-finder.py 
String found where operator expected at admin-finder.py line 15, near """
	(Missing semicolon on previous line?)
String found where operator expected at admin-finder.py line 18, near """""
	(Missing operator before ""?)
Bareword found where operator expected at admin-finder.py line 20, near "logger"
	(Missing semicolon on previous line?)
Bareword found where operator expected at admin-finder.py line 21, near ")
    parser"
	(Missing operator before parser?)
Bareword found where operator expected at admin-finder.py line 22, near ")
    parser"
	(Missing operator before parser?)
Bareword found where operator expected at admin-finder.py line 23, near ")
    parser"
	(Missing operator before parser?)
Bareword found where operator expected at admin-finder.py line 24, near ")
    parser"
	(Missing operator before parser?)
Bareword found where operator expected at admin-finder.py line 25, near ")
    parser"
	(Missing operator before parser?)
Bareword found where operator expected at admin-finder.py line 27, near ")

    args"
	(Missing operator before args?)
Bareword found where operator expected at admin-finder.py line 43, near "args"
	(Missing semicolon on previous line?)
Bareword found where operator expected at admin-finder.py line 49, near ")
        args"
	(Missing operator before args?)
Bareword found where operator expected at admin-finder.py line 51, near ")

    robot_handler"
	(Missing operator before robot_handler?)
Bareword found where operator expected at admin-finder.py line 52, near ")
    result"
	(Missing operator before result?)
Bareword found where operator expected at admin-finder.py line 60, near ")
        choice"
	(Missing operator before choice?)
Bareword found where operator expected at admin-finder.py line 64, near ")

    try"
	(Missing operator before try?)
Bareword found where operator expected at admin-finder.py line 66, near ")
        workerPool"
	(Missing operator before workerPool?)
Bareword found where operator expected at admin-finder.py line 69, near ")
            thread"
	(Missing operator before thread?)
Bareword found where operator expected at admin-finder.py line 71, near ")
            workerPool"
	(Missing operator before workerPool?)
Bareword found where operator expected at admin-finder.py line 76, near ")

        logger"
	(Missing operator before logger?)
String found where operator expected at admin-finder.py line 89, near "║ ,-. ,-| ,-,-. . ,-.   ,""
	(Missing semicolon on previous line?)
syntax error at admin-finder.py line 14, near "):"

**Comment by the-c0d3r** [comment]
You're not kidding right? It is a python program, you can deduce it by the name admin-finder.**py**, or from the README page.

> Multi-threaded admin finder written in python

I assumed everyone would know that you need to use `python` to run python programs.

```bash
python3 admin-finder.py -u www.google.com -t 100
```

**Comment by ramvirsingh660** [comment]
[image: image.png]

**Comment by the-c0d3r** [comment]
Issue closed, as there are no more comments.
