### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by sc2323-90** [the-c0d3r/admin-finder#14]
I'm getting in trouble

Would you like to continue scanning?
[y]/n: y
Traceback (most recent call last):
  File "adminfinder.py", line 125, in <module>
    main()
  File "adminfinder.py", line 99, in main
    semaphore = asyncio.Semaphore(args.threadcount)
  File "C:\Python38\lib\asyncio\locks.py", line 453, in __init__
    if value < 0:
TypeError: '<' not supported between instances of 'str' and 'int'

how about a solution???

**Comment by the-c0d3r** [comment]
can you show the whole traceback? What's the argument you used to run the program?

**Comment by sc2323-90** [comment]
i have run on

**C:\admin-finder>python adminfinder.py -u https://example.com/ -w wordlist.txt -t 10x**

and response

    **╔════════════════════════════════════════════╗
    ║               .          .                 ║
    ║ ,-. ,-| ,-,-. . ,-.   ," . ,-. ,-| ,-. ,-. ║
    ║ ,-| | | | | | | | |   |- | | | | | |-' |   ║
    ║ `-^ `-^ ' ' ' ' ' '   |  ' ' ' `-^ `-' '   ║
    ║                       '          the-c0d3r ║
    ╚════════════════════════════════════════════╝
    [0m
[+] Detected robot file at https://kab-bogor.kpu.go.id/robots.txt
[+] Detected keywords in robot file
------------------------------
/joomla/administrator/
/administrator/
/joomla/administrator/
/administrator/
------------------------------
Would you like to continue scanning?
[y]/n: y
Traceback (most recent call last):
  File "adminfinder.py", line 125, in <module>
    main()
  File "adminfinder.py", line 99, in main
    semaphore = asyncio.Semaphore(args.threadcount)
  File "C:\Python38\lib\asyncio\locks.py", line 453, in __init__
    if value < 0:
TypeError: '<' not supported between instances of 'str' and 'int'**


am I wrong running this program? or can you provide a solution?

**Comment by sc2323-90** [comment]
i have run with

**C:\admin-finder>python adminfinder.py -u https://example.com/ -w wordlist.txt -t 10x**


and respon

**[91m
    ╔════════════════════════════════════════════╗
    ║               .          .                 ║
    ║ ,-. ,-| ,-,-. . ,-.   ," . ,-. ,-| ,-. ,-. ║
    ║ ,-| | | | | | | | |   |- | | | | | |-' |   ║
    ║ `-^ `-^ ' ' ' ' ' '   |  ' ' ' `-^ `-' '   ║
    ║                       '          the-c0d3r ║
    ╚════════════════════════════════════════════╝
    [0m
[+] Detected robot file at https://example.com/robots.txt
[+] Detected keywords in robot file
------------------------------
/joomla/administrator/
/administrator/
/joomla/administrator/
/administrator/
------------------------------
Would you like to continue scanning?
[y]/n: y
Traceback (most recent call last):
  File "adminfinder.py", line 125, in <module>
    main()
  File "adminfinder.py", line 99, in main
    semaphore = asyncio.Semaphore(args.threadcount)
  File "C:\Python38\lib\asyncio\locks.py", line 453, in __init__
    if value < 0:
TypeError: '<' not supported between instances of 'str' and 'int'**

did I run wrong? or can you provide another solution?

**Comment by the-c0d3r** [comment]
`-t 10x` this is where you are supposed to give number, not string. Try without the `x` and it will work. 


```
python adminfinder.py -u https://example.com/ -w wordlist.txt -t 10
```

**Comment by the-c0d3r** [comment]
Closing issue as the user error was fixed and no more news from the author.
