### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by IgorGradov** [the-c0d3r/admin-finder#2]
https://github.com/the-c0d3r/admin-finder/blob/1066557983e0748847f28157dd0d6d6c31b69b67/admin-finder.py#L70 print/print()

**Comment by the-c0d3r** [comment]
Why bother posting an issue about 2.7 vs 3.x? Create a PR if you wish. I'm closing this.

https://pythonclock.org/ Refer to this to see how long until 2.7 is deprecated.
